spring.application.name=hr-spring

# DB 접속 정보
spring.datasource.url=SECRET_REMOVED
spring.datasource.username=SECRET_REMOVED
spring.datasource.password=SECRET_REMOVED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true