spring.application.name=hr-spring
server.port=8080

logging.level.org.springframework=info
logging.level.org.springframework.web=info

# Database Setting
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hr
spring.datasource.username=SECRET_REMOVED
spring.datasource.password=ksw7035

# JPA Setting
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect